name: CI

on: [push, pull_request]

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    env:
      BOTO_CONFIG: /dev/null
      AWS_ACCESS_KEY_ID: foobar_key
      AWS_SECRET_ACCESS_KEY: foobar_secret

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup conda
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci/env.yaml
          extra-specs: python=${{ matrix.python-version }}

      - name: Install
        shell: bash -l {0}
        run: |
          pip install git+https://github.com/fsspec/filesystem_spec
          pip install . --no-deps

      - name: Run Tests
        shell: bash -l {0}
        run: pytest -vv s3fs


  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
